ProjectName:
  %PROJECT_NAME%

RootPath:
  "%ROOT_PATH%"

LogoPath:
  "%LOGO_PATH%"

DocumentationPath:
  "%DOCUMENTATION_PATH%"

FilesToProcessPaths:
  - "%FILE_NAME%"

RepositoryURL:
  %REPOSITORY_URL%

FilesToLinterCheck:
  - "test.cpp"
  - "test.h"