ProjectName:
  %PROJECT_NAME%

RootPath:
  "%ROOT_PATH%"

LogoPath:
  "%LOGO_PATH%"

DocumentaionPath:
  "%DOCUMENTATION_PATH%"

Theme:
  %THEME%

FilesToProcessPaths:
  - "%FILE_NAME%"

RepositoryURL:
  %REPOSITORY_URL%